import { AndreaMapPlace, MapCameraState } from '../../types/map';

export const DEFAULT_MAP_CAMERA: MapCameraState = {
  latitude: 39.4699,
  longitude: -0.3763,
  zoom: 11.5,
};

export const DEMO_MAP_PLACES: AndreaMapPlace[] = [
  {
    id: 'demo-memory-first-date',
    type: 'memory',
    title: 'Nuestra primera cita',
    subtitle: 'Ciutat Vella, Valencia',
    description: 'Un café tranquilo y un paseo inolvidable bajo los árboles iluminados de la ciudad.',
    latitude: 39.4750,
    longitude: -0.3780,
    precision: 'exact',
    date: '14 de febrero, 2026',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
  },
  {
    id: 'demo-restaurant-pending',
    type: 'restaurant',
    title: 'Kibo Omakase',
    subtitle: 'Ruzafa, Valencia',
    description: 'Barra íntima japonesa guardada para celebrar nuestro próximo momento especial.',
    latitude: 39.4628,
    longitude: -0.3739,
    precision: 'approximate',
    imageUrl: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=600&q=80',
  },
  {
    id: 'demo-future-place',
    type: 'future_place',
    title: 'Atardecer en barca',
    subtitle: 'La Albufera, El Saler',
    description: 'Paseo en barca al caer la tarde mirando los reflejos dorados sobre el agua.',
    latitude: 39.3300,
    longitude: -0.3330,
    precision: 'city',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
  },
  {
    id: 'demo-beach-walk',
    type: 'memory',
    title: 'Paseo frente al mar',
    subtitle: 'La Malvarrosa, Costa',
    description: 'Conversación infinita escuchando las olas y respirando aire fresco.',
    latitude: 39.4820,
    longitude: -0.3250,
    precision: 'exact',
    date: '28 de mayo, 2026',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
  },
  {
    id: 'demo-surprise-plan',
    type: 'surprise',
    title: 'Plan Secreto en Terraza',
    subtitle: 'Vistas al Puerto',
    description: 'Detalles reservados. Se revelarán cuando llegue la fecha programada.',
    latitude: 39.4580,
    longitude: -0.3320,
    precision: 'exact',
    isRevealed: false,
  },
  {
    id: 'demo-trip-rome',
    type: 'trip',
    title: 'Escapada a Roma',
    subtitle: 'Trastevere, Italia',
    description: 'Calles empedradas, helados al atardecer y luz dorada en la ciudad eterna.',
    latitude: 41.9028,
    longitude: 12.4964,
    precision: 'city',
    date: 'Octubre 2026',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&q=80',
  },
];
