import { AndreaMapPlace, MapCameraState } from '../../types/map';

export const DEFAULT_MAP_CAMERA: MapCameraState = {
  latitude: 39.4699,
  longitude: -0.3763,
  zoom: 12.5,
};

export const MAP_CLUSTER_CONFIG = {
  radius: 58,
  maxZoom: 16,
  showIndividualPinsAtZoom: 13,
  showShortLabelAtZoom: 16,
} as const;

export const DEMO_MAP_PLACES: AndreaMapPlace[] = [
  {
    "id": "milestone-nos-conocimos",
    "type": "memory",
    "title": "Donde nos conocimos",
    "subtitle": "Ent. Rico, 6, Quatre Carreres, 46013 Valencia, Spain",
    "description": "La noche mágica del 23 de noviembre de 2024 donde cruzamos miradas y nos conocimos por primera vez. Esa noche empezó nuestra historia.",
    "latitude": 39.4501321,
    "longitude": -0.3534794,
    "precision": "exact",
    "date": "2024-11-23",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Ent. Rico, 6, Quatre Carreres, 46013 Valencia, Spain",
    "city": "Valencia",
    "imageUrl": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop"
  },
  {
    "id": "milestone-primera-cita",
    "type": "restaurant",
    "title": "Nuestra Primera Cita · Alqueria del Pou",
    "subtitle": "Ent. Rico, 6, Quatre Carreres, 46013 Valencia, Spain",
    "description": "Nuestra primera cita oficial en el restaurante Alqueria del Pou. Risas, confidencias y donde supimos que queríamos estar juntos.",
    "latitude": 39.4500841,
    "longitude": -0.3535289,
    "precision": "exact",
    "date": "2024-12-05",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Ent. Rico, 6, Quatre Carreres, 46013 Valencia, Spain",
    "city": "Valencia",
    "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-pasta-passione",
    "type": "restaurant",
    "title": "Primera vez en un italiano · Pasta e Passione",
    "subtitle": "C/ dels Juristes, 5, Ciutat Vella, 46001 València, Valencia, Spain",
    "description": "El 13 de diciembre de 2024. La primera vez que fuimos juntos a un restaurante italiano en Valencia. Pasta deliciosa y risas infinitas.",
    "latitude": 39.475574,
    "longitude": -0.3764674,
    "precision": "exact",
    "date": "2024-12-13",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "C/ dels Juristes, 5, Ciutat Vella, 46001 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-tercera-cita-virgen",
    "type": "memory",
    "title": "Nuestra Tercera Cita · Paseo por Plaza de la Virgen",
    "subtitle": "Plaça de la Mare de Déu, Ciutat Vella, València, Valencia, Spain",
    "description": "El 15 de diciembre de 2024 paseando por la calle y la Plaza de la Virgen iluminada, sintiendo cada vez más complicidad y magia.",
    "latitude": 39.476283,
    "longitude": -0.3755307,
    "precision": "exact",
    "date": "2024-12-15",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Plaça de la Mare de Déu, Ciutat Vella, València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-primera-foto-padres",
    "type": "memory",
    "title": "La primera foto que le enviamos a sus padres",
    "subtitle": "C/ de Sant Martí, 1, Ciutat Vella, 46002 València, Valencia, Spain",
    "description": "El 27 de diciembre de 2024 (dos semanas después de las primeras citas): la primera fotografía que compartimos con la familia con toda la ilusión del mundo.",
    "latitude": 39.4734652,
    "longitude": -0.3757007,
    "precision": "exact",
    "date": "2024-12-27",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "C/ de Sant Martí, 1, Ciutat Vella, 46002 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-honest-greens",
    "type": "restaurant",
    "title": "Cuando descubrimos Honest Greens",
    "subtitle": "C/ dels Cavallers, 24, Ciutat Vella, 46001 València, Valencia, Spain",
    "description": "El 30 de diciembre de 2024: el día que descubrimos nuestro rincón favorito de comida rica y saludable en la calle Caballeros.",
    "latitude": 39.476716,
    "longitude": -0.3780408,
    "precision": "exact",
    "date": "2024-12-30",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "C/ dels Cavallers, 24, Ciutat Vella, 46001 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-etapa-canet",
    "type": "trip",
    "title": "Nuestra etapa en Canet d'en Berenguer",
    "subtitle": "46529 Canet d'en Berenguer, Valencia, Spain",
    "description": "Desde el 5 de enero de 2025 hasta noviembre de 2025: meses maravillosos viviendo junto al mar, atardeceres y paseos infinitos.",
    "latitude": 39.6855392,
    "longitude": -0.2066769,
    "precision": "exact",
    "date": "2025-01-05",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "46529 Canet d'en Berenguer, Valencia, Spain",
    "city": "Canet d'en Berenguer",
    "imageUrl": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-segundo-airbnb",
    "type": "memory",
    "title": "Nuestro Segundo Airbnb Romántico",
    "subtitle": "Carrer de la Bosseria, Ciutat Vella, 46001 València, Valencia, Spain",
    "description": "Del 21 al 23 de enero de 2025. Un recuerdo sumamente especial para los dos: fue aquí donde nos dimos cuenta de que estábamos profundamente enamorados el uno del otro.",
    "latitude": 39.4752818,
    "longitude": -0.379935,
    "precision": "exact",
    "date": "2025-01-21",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Carrer de la Bosseria, Ciutat Vella, 46001 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&auto=format&fit=crop"
  },
  {
    "id": "restaurant-don-salvatore",
    "type": "restaurant",
    "title": "Cena en Ristorante Don Salvatore",
    "subtitle": "Carrer del Comte d'Altea, 48, L'Eixample, 46005 València, Valencia, Spain",
    "description": "El 22 de enero de 2025 cenando pasta auténtica italiana en Don Salvatore durante nuestros días de Airbnb.",
    "latitude": 39.4670943,
    "longitude": -0.3652271,
    "precision": "exact",
    "date": "2025-01-22",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Carrer del Comte d'Altea, 48, L'Eixample, 46005 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-conocer-padres-manises",
    "type": "memory",
    "title": "Primera vez que fui a conocer a sus padres",
    "subtitle": "Carrer Xàtiva, 25, 46940 Manises, Valencia, Spain",
    "description": "El 28 de enero de 2025 en Carrer Xàtiva 25, Manises. Una tarde llena de emoción, acogida y el comienzo de muchísimos momentos con su familia.",
    "latitude": 39.49658360000001,
    "longitude": -0.4729724,
    "precision": "exact",
    "date": "2025-01-28",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Carrer Xàtiva, 25, 46940 Manises, Valencia, Spain",
    "city": "Manises",
    "imageUrl": "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-merienda-mercado-colon",
    "type": "restaurant",
    "title": "Sitio que nos encantó merendar · Mercado de Colón",
    "subtitle": "Carrer de Jorge Juan, 19, L'Eixample, 46004 València, Valencia, Spain",
    "description": "El 11 de febrero de 2025: merienda deliciosa y café en nuestro rincón favorito cerca del Mercado de Colón.",
    "latitude": 39.4689685,
    "longitude": -0.3683553,
    "precision": "exact",
    "date": "2025-02-11",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Carrer de Jorge Juan, 19, L'Eixample, 46004 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop"
  },
  {
    "id": "memory-tercer-mejor-airbnb",
    "type": "memory",
    "title": "Nuestro Tercer y Mejor Airbnb Romántico",
    "subtitle": "Pg. de l'Albereda, València, Valencia, Spain",
    "description": "Del 13 al 16 de febrero de 2025. El mejor fin de semana de nuestras vidas: San Valentín, complicidad absoluta y nuestro compromiso oficial de empezar a salir juntos.",
    "latitude": 39.4643774,
    "longitude": -0.3584919,
    "precision": "exact",
    "date": "2025-02-13",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Pg. de l'Albereda, València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&auto=format&fit=crop"
  },
  {
    "id": "restaurant-casa-daragona-sanvalentin",
    "type": "restaurant",
    "title": "San Valentín en Ristorante Casa d'Aragona",
    "subtitle": "Carrer de Ciscar, 12, L'Eixample, 46005 València, Valencia, Spain",
    "description": "El 14 de febrero de 2025: cena romántica de San Valentín a la luz de las velas en Casa d'Aragona.",
    "latitude": 39.4668802,
    "longitude": -0.3663839,
    "precision": "exact",
    "date": "2025-02-14",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Carrer de Ciscar, 12, L'Eixample, 46005 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop"
  },
  {
    "id": "milestone-primer-beso-pareja",
    "type": "memory",
    "title": "Primer Beso & Donde Empezamos a Salir",
    "subtitle": "Pg. de l'Albereda, 44, Camins al Grau, 46023 València, Valencia, Spain",
    "description": "El 15 de febrero de 2025 en el Paseo de la Alameda, 44. El rincón mágico de nuestro primer beso y donde Tonet le pidió salir a Andrea. El comienzo oficial de nuestro camino juntos.",
    "latitude": 39.4586501,
    "longitude": -0.3508072,
    "precision": "exact",
    "date": "2025-02-15",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Pg. de l'Albereda, 44, Camins al Grau, 46023 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&auto=format&fit=crop"
  },
  {
    "id": "place-casa-tonet",
    "type": "memory",
    "title": "Casa de Tonet · Conde de Real",
    "subtitle": "Carrer Comte Del Real, 16, 46194 Real, Valencia, Spain",
    "description": "Nuestro hogar y refugio de amor compartido en Valencia.",
    "latitude": 39.3351766,
    "longitude": -0.6113263999999999,
    "precision": "exact",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Carrer Comte Del Real, 16, 46194 Real, Valencia, Spain",
    "city": "Real",
    "imageUrl": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop"
  },
  {
    "id": "restaurant-latte-farina",
    "type": "restaurant",
    "title": "Cuando fuimos a Latte & Farina",
    "subtitle": "Pl. del Miracle del Mocadoret, 6, Ciutat Vella, 46001 València, Valencia, Spain",
    "description": "El 10 de mayo de 2025: comida italiana deliciosa y postres artesanales en una de las plazas más bonitas del centro.",
    "latitude": 39.4743521,
    "longitude": -0.3762955,
    "precision": "exact",
    "date": "2025-05-10",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Pl. del Miracle del Mocadoret, 6, Ciutat Vella, 46001 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop"
  },
  {
    "id": "restaurant-casa-daragona-mayo",
    "type": "restaurant",
    "title": "Cena en Casa d'Aragona (Mayo)",
    "subtitle": "Carrer de Ciscar, 12, L'Eixample, 46005 València, Valencia, Spain",
    "description": "El 11 de mayo de 2025: otra cena inolvidable compartiendo pasta fresca en Casa d'Aragona.",
    "latitude": 39.4668802,
    "longitude": -0.3663839,
    "precision": "exact",
    "date": "2025-05-11",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "Carrer de Ciscar, 12, L'Eixample, 46005 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop"
  },
  {
    "id": "restaurant-le-favole",
    "type": "restaurant",
    "title": "Cuando fuimos a Ristorante Le Favole",
    "subtitle": "C/ de l'Hedra, 5, Ciutat Vella, 46001 València, Valencia, Spain",
    "description": "En el verano de 2025: noche cálida de risas, confidencias y gastronomía italiana en la terraza de Le Favole.",
    "latitude": 39.4722365,
    "longitude": -0.3784505,
    "precision": "exact",
    "date": "2025-07-15",
    "source": "google_places",
    "verifiedByUser": true,
    "formattedAddress": "C/ de l'Hedra, 5, Ciutat Vella, 46001 València, Valencia, Spain",
    "city": "València",
    "imageUrl": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop"
  }
];
