import { AndreaMapPlace, MapCameraState } from '../../types/map';

export const DEFAULT_MAP_CAMERA: MapCameraState = {
  latitude: 39.4699,
  longitude: -0.3763,
  zoom: 11.5,
};

export const DEMO_MAP_PLACES: AndreaMapPlace[] = [
  {
    id: 'milestone-primer-beso-pareja',
    type: 'memory',
    title: 'Primer Beso & Donde Empezamos a Salir',
    subtitle: "Pg. de l'Albereda, 44, Camins al Grau, Valencia",
    description: "El 15 de febrero de 2025 en el Paseo de la Alameda, 44. El rincón mágico de nuestro primer beso y donde Ángel le pidió salir a Andrea. El comienzo oficial de nuestro camino juntos.",
    latitude: 39.4632,
    longitude: -0.3546,
    precision: 'exact',
    date: '15 de febrero, 2025',
    imageUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&auto=format&fit=crop',
  },
  {
    id: 'milestone-nos-conocimos',
    type: 'memory',
    title: 'Donde nos conocimos',
    subtitle: 'Ent. Rico, 6, Quatre Carreres, Valencia',
    description: 'La noche mágica del 23 de noviembre de 2024 donde cruzamos miradas y nos conocimos por primera vez. Esa noche empezó nuestra historia.',
    latitude: 39.4497,
    longitude: -0.3672,
    precision: 'exact',
    date: '23 de noviembre, 2024',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop',
  },
  {
    id: 'milestone-primera-cita',
    type: 'restaurant',
    title: 'Nuestra Primera Cita · Alqueria del Pou',
    subtitle: "Entrada del Pou d'Aparisi, 2, Quatre Carreres, Valencia",
    description: 'Nuestra primera cita oficial en el restaurante Alqueria del Pou. Risas, confidencias y donde supimos que queríamos estar juntos.',
    latitude: 39.4491,
    longitude: -0.3664,
    precision: 'exact',
    date: 'Diciembre, 2024',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop',
  },
  {
    id: 'demo-restaurant-pending',
    type: 'restaurant',
    title: 'Kibo Omakase',
    subtitle: 'Ruzafa, Valencia',
    description: 'Barra íntima japonesa guardada para celebrar nuestro próximo momento especial.',
    latitude: 39.4628,
    longitude: -0.3739,
    precision: 'approximate',
    imageUrl: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=600&q=80',
  },
  {
    id: 'demo-future-place',
    type: 'future_place',
    title: 'Atardecer en barca',
    subtitle: 'La Albufera, El Saler',
    description: 'Paseo en barca al caer la tarde mirando los reflejos dorados sobre el agua.',
    latitude: 39.3300,
    longitude: -0.3330,
    precision: 'city',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
  },
  {
    id: 'demo-beach-walk',
    type: 'memory',
    title: 'Paseo frente al mar',
    subtitle: 'La Malvarrosa, Costa',
    description: 'Conversación infinita escuchando las olas y respirando aire fresco.',
    latitude: 39.4820,
    longitude: -0.3250,
    precision: 'exact',
    date: '28 de mayo, 2026',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
  },
  {
    id: 'demo-surprise-plan',
    type: 'surprise',
    title: 'Plan Secreto en Terraza',
    subtitle: 'Vistas al Puerto',
    description: 'Detalles reservados. Se revelarán cuando llegue la fecha programada.',
    latitude: 39.4580,
    longitude: -0.3320,
    precision: 'exact',
    isRevealed: false,
  },
  {
    id: 'demo-trip-rome',
    type: 'trip',
    title: 'Escapada a Roma',
    subtitle: 'Trastevere, Italia',
    description: 'Calles empedradas, helados al atardecer y luz dorada en la ciudad eterna.',
    latitude: 41.9028,
    longitude: 12.4964,
    precision: 'city',
    date: 'Octubre 2026',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&q=80',
  },
];
