import { RomanticIdea } from './calendar.types';

export const ROMANTIC_IDEAS_CATALOG: RomanticIdea[] = [
  {
    id: 'idea-surprise',
    title: 'Modo Sorpresa',
    subtitle: 'Prepara algo especial sin que tu pareja lo vea antes de tiempo.',
    emoji: '🎁',
    category: 'sorprender',
    description: 'Crea una cena secreta, un detalle, una escapada o un regalo. Configura cuándo se revela para mantener la ilusión intacta.',
    actionLabel: 'Activar modo',
    modeType: 'surprise',
  },
  {
    id: 'idea-random-date',
    title: 'Cita Aleatoria',
    subtitle: 'Dejad que la app proponga una idea para esta semana.',
    emoji: '🎲',
    category: 'salir',
    description: 'Genera un plan según el tiempo disponible, presupuesto o estado de ánimo. Si os gusta, guardadlo como plan directamente en el calendario.',
    actionLabel: 'Generar cita',
    modeType: 'random_date',
  },
  {
    id: 'idea-future-letter',
    title: 'Carta para el Futuro',
    subtitle: 'Escribe un mensaje que se abrirá en una fecha especial.',
    emoji: '💌',
    category: 'hablar',
    description: 'Deja una carta de amor, un deseo o una cápsula del tiempo que se desbloqueará en vuestro aniversario o cumpleaños.',
    actionLabel: 'Escribir carta',
    modeType: 'future_letter',
  },
  {
    id: 'idea-screen-free',
    title: 'Noche sin Pantallas',
    subtitle: 'Reservad una noche solo para vosotros dos.',
    emoji: '🌙',
    category: 'conectar',
    description: 'Una cena con velas, música suave y conversación sin teléfonos. Un ritual simple que recarga la conexión.',
    actionLabel: 'Programar noche',
    modeType: 'screen_free',
  },
  {
    id: 'idea-sunday-ritual',
    title: 'Ritual del Domingo',
    subtitle: '¿Qué ha sido lo mejor de nuestra semana?',
    emoji: '🌿',
    category: 'conectar',
    description: 'Un momento tranquilo cada fin de semana para agradecer 3 cosas bonitas que habéis vivido juntos.',
    actionLabel: 'Activar ritual',
    modeType: 'ritual',
  },
  {
    id: 'idea-escapade',
    title: 'Planear una Escapada',
    subtitle: 'Un fin de semana fuera para romper la rutina.',
    emoji: '✈️',
    category: 'salir',
    description: 'Elegid un destino cercano, buscad una cabaña o un rincón tranquilo y marcad la fecha con ilusión.',
    actionLabel: 'Planear viaje',
  },
  {
    id: 'idea-home-cinema',
    title: 'Cine de Casa Especial',
    subtitle: 'Palomitas caseras, manta y aquella película pendiente.',
    emoji: '🎬',
    category: 'casa',
    description: 'Transformad el salón en una pequeña sala de cine privada para desconectar juntos.',
    actionLabel: 'Fijar fecha',
  },
  {
    id: 'idea-memory-capture',
    title: 'Un Recuerdo al Mes',
    subtitle: 'Guardad una foto y una anécdota significativa.',
    emoji: '📸',
    category: 'celebrar',
    description: 'Elegid una foto especial de este mes y guardadla en vuestro Mapa y Diario para construir vuestra historia.',
    actionLabel: 'Guardar foto',
  },
];
